language: node_js
node_js:
  - node
dist: trusty
env:
  global:
    secure: afD2URdDc2I18niwnCNBnT2EWJ3EjddknEZAlPoXCWZ/7wrmVZ1piP2eorN9hbTHFln6FPpm0HXptecv0y4VXckXe5bD6X44mFCCjowuISHMARj46X/kW8+LNrk7qieP22qnec/t513nZEqOXGre0xk88CLyi2QoLkMkZGRkQLfg7ezv3jIt/vxPCZ8fqRz1oJDexJGccDSHwcUQqaIsL9EQmT+qMhKLGKE4M31wVdJPyV0l7i9TGIH7QpXD6wkP/n5rAo8M71AUI525lXdCOhWpyFu9T5Er0fAy4BfR291KeGttPRg/I+tvEHf8PYIJo5FcVcjqhOa1irsVrBodRgE6ZQemcbG/WhGfgYXOCj2ZXQMG9Zsu1NhWHai0FTmdt/vV7H817S8GytgApVwVdbe+xLURntpKWRPy+QlFAQo3a3iSC0JfN3SSI1TC7KXrnsgb93YCpCcKQ/BnO20Aq9lcTXtfeVEyG5Sj0UVxHW87dqS0Wzym6amPdSlZoNApHoG4VeIzbqgDz3TrnV6D+U/FSEBTaFFlSmDp7us/CUg7WagEQt98imwdMLwpg4j24o+U8QTOEb/CFQ4jf7mSkK2EmlBzsCXcJz0/1hfpqofp+/djbEswNa4vkhrxS0fTTXo1Vn9jptAyCUN8sbL8bE8UDfw/Ah7CFKaCkiONUdo=
sudo: false
cache: yarn
script:
  - yarn run coveralls